[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

[api]
dashboard = true
insecure = true

[providers.docker]
exposedByDefault = false
watch=true

[certificatesResolvers]
[certificatesResolvers.default]
[certificatesResolvers.default.acme]
email = "julien.calise@orange.fr"
storage = "acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
[certificatesResolvers.default.acme.tlsChallenge]

# Redirection automatique du trafic HTTP vers HTTPS
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"
