[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

[api]
dashboard = true
insecure = true

[providers.docker]
exposedByDefault = false
[providers.file]
directory = "/providers/"
watch = true

[certificatesResolvers]
[certificatesResolvers.le-resolver]
[certificatesResolvers.le-resolver.acme]
email = "julien.calise@orange.fr"
storage = "acme.json"
[certificatesResolvers.le-resolver.acme.tlsChallenge]

# Redirection automatique du trafic HTTP vers HTTPS
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"
