version: '3.9'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ../mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: "phpmyadmin"
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    links:
      - database

  php:
    container_name: php
    image: thecodingmachine/php:8.1-v4-apache-node16
    volumes:
      - ../app:/var/www/html:rw
    depends_on:
      - database
    restart: always
