name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ~/SitePortFolio/
            git pull -v
            cd ~/SitePortFolio/.docker/
            docker-compose down
            docker-compose up -d
            cd ~/SitePortfolio/app/
            docker exec -it php /bin/bash -c "cd /var/www/html/app && npm install && npm run build"
